### ISSUE TITLE
[Question] Use of Links

### ISSUE THREAD

**Issue by bearrito** [davidban77/ansible-molecule-demo#10]
How do links work in your example - https://github.com/networktocode/interop2020-ansible-molecule/blob/master/molecule/mock/molecule.yml#L28

I could not find any documentation on this. Basically how are you referring to the various machines?

**Comment by davidban77** [comment]
Under the hood is docker compose when you set docker as the provider, so you have some capabilities exposed like [link-containers](https://docs.docker.com/compose/networking/#link-containers).

So at the end -> `Links allow you to define extra aliases by which a service is reachable from another service` and this helps on setting it up on the `platforms` section in the `molecule.yml` so you can just reference the service name.

**Comment by bearrito** [comment]
@davidban77  Thanks for responding. I ended up sorting this out after digging through the code base a bit. 
Links didn't work for me in any case. I had a bit  more complex use case with static ips, using IPAM. I had to to etc_aliases.
